# Generated by Django 4.2 on 2025-11-28 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control_escolar_desit_api', '0004_maestros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nrc', models.IntegerField(blank=True, null=True)),
                ('nombre_materia', models.CharField(blank=True, max_length=255, null=True)),
                ('seccion', models.IntegerField(blank=True, null=True)),
                ('dias_json', models.TextField(blank=True, null=True)),
                ('hora_inicial', models.CharField(blank=True, max_length=255, null=True)),
                ('hora_final', models.CharField(blank=True, max_length=255, null=True)),
                ('salon', models.CharField(blank=True, max_length=255, null=True)),
                ('programa_educativo', models.CharField(blank=True, max_length=255, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
