# Generated by Django 4.2 on 2025-11-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_desit_api', '0005_materias'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='creditos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
