# Generated by Django 4.2 on 2025-11-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_desit_api', '0006_materias_creditos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materias',
            name='user',
        ),
        migrations.AlterField(
            model_name='materias',
            name='dias_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
