# Generated by Django 4.2 on 2025-12-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_desit_api', '0007_remove_materias_user_alter_materias_dias_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='profesores',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
