# Generated by Django 4.2 on 2025-12-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_desit_api', '0008_materias_profesores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materias',
            old_name='profesores',
            new_name='profesor',
        ),
    ]
